IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='Sites')
BEGIN
	CREATE TABLE [dbo].[Sites] (	
	    [Id] INT CONSTRAINT PK_Sites_Id PRIMARY KEY NOT NULL,
		[Name] VARCHAR(500)	NOT NULL
	);
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='AccessPoints')
BEGIN
	CREATE TABLE [dbo].[AccessPoints] (	
	    [Id] INT CONSTRAINT PK_AccessPoints_Id PRIMARY KEY NOT NULL,
		[Name] VARCHAR(500)	NOT NULL,
		[SiteId] int CONSTRAINT FK_AccessPoints_SiteId FOREIGN KEY REFERENCES Sites(Id) NOT NULL
	);
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='Departments')
BEGIN
	CREATE TABLE [dbo].[Departments] (	
	    [Id] INT CONSTRAINT PK_Departments_Id PRIMARY KEY NOT NULL,
		[Name] VARCHAR(500)	NOT NULL --no manager here
	);
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='Employees')
BEGIN
	CREATE TABLE [dbo].[Employees] (	
	    --[Id] INT IDENTITY(1,1) CONSTRAINT PK_Employees_Id PRIMARY KEY NOT NULL,
		[Id] INT CONSTRAINT PK_Employees_Id PRIMARY KEY NOT NULL, --[Login]
		[Name] VARCHAR(500)	NOT NULL,
		[Email] VARCHAR(200) NOT NULL,
		--[Id] INT	CONSTRAINT UK_Employees_Login UNIQUE NOT NULL,
		[Password] VARCHAR(50) NOT NULL,
		[Domain] VARCHAR(50) NOT NULL,
		[DepartmentId] int CONSTRAINT FK_Employees_DepartmentId FOREIGN KEY REFERENCES Departments(Id) NOT NULL
	);
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='DepartmentManagers')
BEGIN
	CREATE TABLE [dbo].[DepartmentManagers] (	
	    [Id] INT IDENTITY(1,1) CONSTRAINT PK_DepartmentManagers_Id PRIMARY KEY NOT NULL,
		[DepartmentId] int CONSTRAINT FK_DepartmentManagers_DepartmentId FOREIGN KEY REFERENCES Departments(Id) NOT NULL,
		[ManagerId] int CONSTRAINT FK_DepartmentManagers_ManagerId FOREIGN KEY REFERENCES Employees(Id) NOT NULL
	);
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='UserGroups')
BEGIN
	CREATE TABLE [dbo].[UserGroups] (	
	    [Id] INT CONSTRAINT PK_UserGroups_Id PRIMARY KEY NOT NULL,
		[Name] VARCHAR(500)	NOT NULL
	);
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='UserGroupMappings')
BEGIN
	CREATE TABLE [dbo].[UserGroupMappings] (	
	    [Id] INT IDENTITY(1,1) CONSTRAINT PK_UserGroupMappings_Id PRIMARY KEY NOT NULL,
		[UserGroupId] int CONSTRAINT FK_UserGroupMappings_UserGroupId FOREIGN KEY REFERENCES UserGroups(Id) NOT NULL,
		[EmployeeId] int CONSTRAINT FK_UserGroupMappings_EmployeeId FOREIGN KEY REFERENCES Employees(Id) NOT NULL
	);
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='AccessTypes')
BEGIN
	CREATE TABLE [dbo].[AccessTypes] (	
	    [Id] INT CONSTRAINT PK_AccessTypes_Id PRIMARY KEY NOT NULL,
		[Name] VARCHAR(100)	NOT NULL
	);
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='UserPermissions')
BEGIN
	CREATE TABLE [dbo].[UserPermissions] (	
	    [Id] INT IDENTITY(1,1) CONSTRAINT PK_UserPermissions_Id PRIMARY KEY NOT NULL,
		[EmployeeId] int CONSTRAINT FK_UserPermissions_EmployeeId FOREIGN KEY REFERENCES Employees(Id) NOT NULL,
		[AccessPointId] int CONSTRAINT FK_UserPermissions_AccessPointId FOREIGN KEY REFERENCES AccessPoints(Id) NOT NULL,
		[AccessTypeId] int CONSTRAINT FK_UserPermissions_AccessTypeId FOREIGN KEY REFERENCES AccessTypes(Id) NOT NULL
	);
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='AccessLevels')
BEGIN
	CREATE TABLE [dbo].[AccessLevels] (	
	    [Id] INT CONSTRAINT PK_AccessLevels_Id PRIMARY KEY NOT NULL,
		[Name] VARCHAR(100)	NOT NULL
	);
END
GO